<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\FormPSS;

class FormPSSSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        // $query = array(
        //     array(
        //         'municipality_id' => 1,
        //         'patient_name' => 'Maeron Reyes',
        //         'home_address' => "Racquel Burbos",
        //         'hospital_id' => 1,
        //         'date' => '2023-05-29',
        //         'date_in' => 1,
        //         'date_out' => "1",
        //         'checked_doctor' => "1",
        //         'before_admit' => "1",
        //         'radio1_a' => "1",
        //         'radio1_b' => "1",
        //         'radio1_c' => "1",
        //         'radio1_d' => "1",
        //         'radio1_e' => "1",
        //         'radio1_f' => "1",
        //         'radio1_g' => "1",
        //         'radio2_a' => "1",
        //         'radio2_b' => "1",
        //         'radio2_c' => "1",
        //         'radio2_d' => "1",
        //         'radio2_e' => "1",
        //         'radio3_a' => "1",
        //         'radio3_b' => "1",
        //         'radio3_c' => "1",
        //         'radio3_d' => "1",
        //         'radio3_e' => "1",
        //         'radio4_a' => "1",
        //         'radio4_b' => "1",
        //         'radio4_c' => "1",
        //         'radio4_d' => "1",
        //         'radio5_a' => "1",
        //         'radio5_b' => "1",
        //         'radio5_c' => "1",
        //         'radio5_d' => "1",
        //         'radio5_e' => "1",
        //         'radio6_a' => "1",
        //         'radio6_b' => "1",
        //         'radio6_c' => "1",
        //         'radio6_d' => "1",
        //         'radio6_e' => "1",
        //         'radio7_a' => "1",
        //         'radio7_b' => "1",
        //         'radio7_c' => "1",
        //         'radio7_d' => "1",
        //         'radio7_e' => "1",
        //         'radio8_a' => "1",
        //         'radio8_b' => "1",
        //         'radio8_c' => "1",
        //         'radio8_d' => "1",
        //         'radio8_e' => "1",
        //         'radio9_a' => "1",
        //         'radio9_b' => "1",
        //         'radio9_c' => "1",
        //         'radio9_d' => "1",
        //         'radio9_e' => "1",
        //         'radio10_a' => "1",
        //         'radio10_b' => "1",
        //         'radio10_c' => "1",
        //         'radio10_d' => "1",
        //         'radio10_e' => "1",
        //         'radio11_a' => "1",
        //         'radio11_b' => "1",
        //         'radio11_c' => "1",
        //         'radio11_d' => "1",
        //         'radio12_a' => "1",
        //         'radio12_b' => "1",
        //         'radio12_c' => "1",
        //         'radio12_d' => "1",
        //         'radio12_e' => "1",
        //         'radio13_a' => "1",
        //         'radio13_b' => "1",
        //         'radio13_c' => "1",
        //         'radio13_d' => "1",
        //         'radio13_e' => "1",
        //         'radio14_a' => "1",
        //         'radio14_b' => "1",
        //         'radio14_c' => "1",
        //         'radio14_d' => "1",
        //         'radio14_e' => "1",
        //         'comments' => "1",
        //     ),
        //     array(
        //         'municipality_id' => 1,
        //         'patient_name' => 'Maeron Reyes',
        //         'home_address' => "Racquel Burbos",
        //         'hospital_id' => 1,
        //         'date' => '2023-06-29',
        //         'date_in' => 1,
        //         'date_out' => "1",
        //         'checked_doctor' => "1",
        //         'before_admit' => "1",
        //         'radio1_a' => "2",
        //         'radio1_b' => "1",
        //         'radio1_c' => "1",
        //         'radio1_d' => "1",
        //         'radio1_e' => "1",
        //         'radio1_f' => "1",
        //         'radio1_g' => "1",
        //         'radio2_a' => "1",
        //         'radio2_b' => "1",
        //         'radio2_c' => "1",
        //         'radio2_d' => "1",
        //         'radio2_e' => "1",
        //         'radio3_a' => "1",
        //         'radio3_b' => "1",
        //         'radio3_c' => "1",
        //         'radio3_d' => "1",
        //         'radio3_e' => "1",
        //         'radio4_a' => "1",
        //         'radio4_b' => "1",
        //         'radio4_c' => "1",
        //         'radio4_d' => "1",
        //         'radio5_a' => "1",
        //         'radio5_b' => "1",
        //         'radio5_c' => "1",
        //         'radio5_d' => "1",
        //         'radio5_e' => "1",
        //         'radio6_a' => "1",
        //         'radio6_b' => "1",
        //         'radio6_c' => "1",
        //         'radio6_d' => "1",
        //         'radio6_e' => "1",
        //         'radio7_a' => "1",
        //         'radio7_b' => "1",
        //         'radio7_c' => "1",
        //         'radio7_d' => "1",
        //         'radio7_e' => "1",
        //         'radio8_a' => "1",
        //         'radio8_b' => "1",
        //         'radio8_c' => "1",
        //         'radio8_d' => "1",
        //         'radio8_e' => "1",
        //         'radio9_a' => "1",
        //         'radio9_b' => "1",
        //         'radio9_c' => "1",
        //         'radio9_d' => "1",
        //         'radio9_e' => "1",
        //         'radio10_a' => "1",
        //         'radio10_b' => "1",
        //         'radio10_c' => "1",
        //         'radio10_d' => "1",
        //         'radio10_e' => "1",
        //         'radio11_a' => "1",
        //         'radio11_b' => "1",
        //         'radio11_c' => "1",
        //         'radio11_d' => "1",
        //         'radio12_a' => "1",
        //         'radio12_b' => "1",
        //         'radio12_c' => "1",
        //         'radio12_d' => "1",
        //         'radio12_e' => "1",
        //         'radio13_a' => "1",
        //         'radio13_b' => "1",
        //         'radio13_c' => "1",
        //         'radio13_d' => "1",
        //         'radio13_e' => "1",
        //         'radio14_a' => "1",
        //         'radio14_b' => "1",
        //         'radio14_c' => "1",
        //         'radio14_d' => "1",
        //         'radio14_e' => "1",
        //         'comments' => "1",
        //     )
        // );
        // DB::table('tbl_form_pss')->insert($query);  
        FormPSS::truncate();
        $csvFile = fopen(base_path("database/data/tbl_form_pss.csv"), "r");

        $firstline = true;
        while (($data = fgetcsv($csvFile, 2000, ",")) !== FALSE) {
            if (!$firstline) {
                FormPSS::create([
                    'patient_name' => $data['1'],
                    'home_address' => $data['2'],
                    'hospital_id' => $data['3'],
                    'date' => $data['4'],
                    'date_in' => $data['5'],
                    'date_out' => $data['6'],
                    'checked_doctor' => $data['7'],
                    'before_admit' => $data['8'],
                    'radio1_a' => $data['9'],
                    'radio1_b' => $data['10'],
                    'radio1_c' => $data['11'],
                    'radio1_d' => $data['12'],
                    'radio1_e' => $data['13'],
                    'radio1_f' => $data['14'],
                    'radio1_g' => $data['15'],
                    'radio2_a' => $data['16'],
                    'radio2_b' => $data['17'],
                    'radio2_c' => $data['18'],
                    'radio2_d' => $data['19'],
                    'radio2_e' => $data['20'],
                    'radio3_a' => $data['21'],
                    'radio3_b' => $data['22'],
                    'radio3_c' => $data['23'],
                    'radio3_d' => $data['24'],
                    'radio3_e' => $data['25'],
                    'radio4_a' => $data['26'],
                    'radio4_b' => $data['27'],
                    'radio4_c' => $data['28'],
                    'radio4_d' => $data['29'],
                    'radio5_a' => $data['30'],
                    'radio5_b' => $data['31'],
                    'radio5_c' => $data['32'],
                    'radio5_d' => $data['33'],
                    'radio5_e' => $data['34'],
                    'radio6_a' => $data['35'],
                    'radio6_b' => $data['36'],
                    'radio6_c' => $data['37'],
                    'radio6_d' => $data['38'],
                    'radio6_e' => $data['39'],
                    'radio7_a' => $data['40'],
                    'radio7_b' => $data['41'],
                    'radio7_c' => $data['42'],
                    'radio7_d' => $data['43'],
                    'radio7_e' => $data['44'],
                    'radio8_a' => $data['45'],
                    'radio8_b' => $data['46'],
                    'radio8_c' => $data['47'],
                    'radio8_d' => $data['48'],
                    'radio8_e' => $data['49'],
                    'radio9_a' => $data['50'],
                    'radio9_b' => $data['51'],
                    'radio9_c' => $data['52'],
                    'radio9_d' => $data['53'],
                    'radio9_e' => $data['54'],
                    'radio10_a' => $data['55'],
                    'radio10_b' => $data['56'],
                    'radio10_c' => $data['57'],
                    'radio10_d' => $data['58'],
                    'radio10_e' => $data['59'],
                    'radio11_a' => $data['60'],
                    'radio11_b' => $data['61'],
                    'radio11_c' => $data['62'],
                    'radio11_d' => $data['63'],
                    'radio12_a' => $data['64'],
                    'radio12_b' => $data['65'],
                    'radio12_c' => $data['66'],
                    'radio12_d' => $data['67'],
                    'radio12_e' => $data['68'],
                    'radio13_a' => $data['69'],
                    'radio13_b' => $data['70'],
                    'radio13_c' => $data['71'],
                    'radio13_d' => $data['72'],
                    'radio13_e' => $data['73'],
                    'radio14_a' => $data['74'],
                    'radio14_b' => $data['75'],
                    'radio14_c' => $data['76'],
                    'radio14_d' => $data['77'],
                    'radio14_e' => $data['78'],
                    'comments' => $data['79'],
                ]);
            }
            $firstline = false;
        }

        fclose($csvFile);
    }
}
